services:
  # Backend API
  - type: web
    name: devai-agent-backend
    env: node
    region: oregon
    plan: starter
    buildCommand: |
      npm ci
      npx prisma generate
      npx prisma migrate deploy
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      # Database
      - key: DATABASE_URL
        sync: false
      
      # API Keys
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: OLLAMA_URL
        value: http://localhost:11434
      
      # JWT & Security
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: BCRYPT_ROUNDS
        value: 12
      
      # App Config
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://your-frontend-url.onrender.com
      
      # Redis (si lo usas)
      - key: REDIS_URL
        sync: false
      
      # File Upload
      - key: MAX_FILE_SIZE
        value: 52428800  # 50MB
      - key: UPLOAD_PATH
        value: ./uploads
      
      # Rate Limiting
      - key: RATE_LIMIT_MAX
        value: 100
      - key: RATE_LIMIT_WINDOW
        value: 900000  # 15 min
      
      # Logging
      - key: LOG_LEVEL
        value: info

  # Frontend (React App)
  - type: web
    name: devai-agent-frontend
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Robots-Tag
        value: noindex
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://devai-agent-backend.onrender.com
      - key: REACT_APP_GEMINI_API_KEY
        sync: false
      - key: REACT_APP_GROQ_API_KEY
        sync: false
      - key: REACT_APP_HUGGINGFACE_API_KEY
        sync: false
      - key: REACT_APP_DEFAULT_PROVIDER
        value: gemini
      - key: REACT_APP_DEFAULT_MODEL
        value: gemini-1.5-flash-latest
      - key: GENERATE_SOURCEMAP
        value: false

databases:
  # PostgreSQL Database
  - name: devai-agent-db
    databaseName: devai_agent
    user: devai_user
    region: oregon
    plan: starter